### ISSUE TITLE
Error key "primary" sql

### ISSUE THREAD

**Issue by jere62smi** [GeorgH93/MarriageMaster#116]
Hello, since the last update, I have this error, how do I fix this?
http://bin.mc-imperia.fr/fONDchfi4H

**Comment by GeorgH93** [comment]
It seems there is a problem with updating the config file when custom database field names are used.

Please open the `plugins/MarriageMaster` folder, there should be the `config.yml` and one or more `config.yml.old_vXX` (XX is a number) files. Open the file with the highest number and under `Database.SQL.Tables` there should be an entry called `Fields`, copy it and all it's sub entries into the `config.yml`.
It most likely will be the `PriestID: priest_id` entry.
Example:
```
Database:
  UseUUIDs: true
  UseUUIDSeparators: false
  UUID_Type: auto
  SQL:
    Host: 'localhost'
    Database: 'minecraft'
    User: 'minecraft'
    Tables:
      User: marry_players
      Partner: marry_partners
      Home: marry_home
      Priests: marry_priests
      Fields:
        PriestID: priest_id
```
