### ISSUE TITLE
Option to show warnings in the Action Bar instead of the Chat

### ISSUE THREAD

**Issue by Xelium** [GeorgH93/MarriageMaster#133]
### Feature request

**Feature description**
Option in the Config to make warning messages show up in the Action Bar instead of the Chat.

**How the feature is useful**
It filters the chat to make it really about chatting and gives a clean view. Especially on busy servers.

**Comment by GeorgH93** [comment]
You should be able the change the display location of almost every message. But you are right, the defaults probably should be adjusted.

You can define the display mode for messages by adding a new line with the format like that: `<message name>_SendMethod: <disabled/chat/action_bar/title>`
For example to show the no permission message in the action bar:
```yaml
Language:
  Ingame:
    NoPermission: "&cYou don't have the permission to do that."
    NoPermission_SendMethod: action_bar
```

It also should be an option on the [translation page](https://ptp.pcgamingfreaks.at).
