### ISSUE TITLE
Chat heart in EssentialsX plugin

### ISSUE THREAD

**Issue by steveq7** [GeorgH93/MarriageMaster#179]
### Help request
Chat heart in EssentialsX plugin
**Problem**

Is it possible to add a heart if someone has a Mary to chat in EssentialsX? If it is possible, how?
**What I have tried**

**Comment by GeorgH93** [comment]
Last time I checked, EssentialsX Chat did not support placeholders, but worked well with the Prefix option that you can find in the config. I think what you want would be:
```yaml
Prefix:
  Enable: true
  # Placeholders: {Surname}, {PartnerName}, {PartnerDisplayName}, {StatusHeart}, {MagicHeart}
  String: "<heart>"
  OnLineBeginning: true
```
