### ISSUE TITLE
Marriage Teleportation Glitch

### ISSUE THREAD

**Issue by smuddgge** [GeorgH93/MarriageMaster#281]
### Information
**Environment information**
```yaml
##### Start Marriage Master version info #####
[INFO]: Marriage Master: 2.6.7-Release
[INFO]: Server: git-Purpur-1845 (MC: 1.19.2)
[INFO]: Java: 19.0.1
[INFO]: PlaceholderAPI: 2.11.2
#####  End Marriage Master version info  #####
```

*Online mode*: False
*BungeeCord*: No

**Plugin config**
```yaml
Teleport:
  Delay: false
  # Time in seconds
  DelayTime: 1
  # List of worlds where you can't teleport to
  BlacklistedWorlds: [ BossArena ]
  # This option controls whether a safety check is performed before the player is teleported.
  CheckSafety: true
  # If this option is enabled the partner has to accept the teleport request before the player will be teleported. Only applicable for teleporting to another player.
  RequireConfirmation: false
```

### Details
**Description**  
When standing under a `Trap Door` and your partner teleports, it will teleport them below the block. This lets players glitch under places they are not meant to go.

**Steps to reproduce**  
- Place a block 3 blocks above the ground.
- Stand on that block
- Place a trap door above your head (the second block above that block)

When your partner teleports they will be teleported below.

**Potential fixes**
Like other plugins that use teleport commands, there could be a section in the config that blacklists blocks.
So If I add trap door, a player cannot be standing in a trapdoor when a player teleports to them.

Another option, probably the best, would be to not teleport them to the exact position. If you are unable to: tell the player they are standing in a bad place ect. This could also be a config option.
