### ISSUE TITLE
Default pt-br translation generates MalformedJsonException

### ISSUE THREAD

**Issue by Pryzinho** [GeorgH93/MarriageMaster#318]
### Information
**Environment information**
*Plugin + server version info*:

```
Marriage Master: 2.7.1
Server: git-Paper-196 (MC: 1.20.1)
Java: 17.0.9
Vault: 1.7.3-b131
PlaceholderAPI: 2.11.5
<!-- Replace this with the output of "/marry version". You can run the command in your console or as op ingame. -->

```

*Online mode*: 
yes
*BungeeCord*: 

**Server/crash log**

```
https://gist.github.com/Pryzinho/4753bb5a6161589802e30af1d5ecb953
<!-- Replace this with your crash log / link to your log file -->

```

**Plugin config (optional)**

```
# Language Settings
Language:
  # Defines the used language and the corresponding file used. The corresponding language file will be placed next to the config.yml named: <Language>.yml
  Language: ptbr
  # Options:
  #     Overwrite (deletes all changes from the file and extracts a new language file)
  #     Upgrade (extracts a new language file and copy's all settings from the old language file)
  #     Update (adds the default (english) text values for all missing values, just some basic formatting)
  UpdateMode: Upgrade
<!-- Replace this with details about your config -->
```

### Details
**Description**  

As you can see, seems like a default message translation is malformed
**Steps to reproduce**  

Just set the lang to ptbr
**Expected behavior**  

This warn appearing in your console
**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
