### ISSUE TITLE
Requests for surname changes

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [GeorgH93/MarriageMaster#364]
### Feature request

**Feature description**
Add option in config or requirement always when priest/player who is allowed to set surnames, try to set someone's surname, either 1 of them or both of them need to agree with that surname to be set, maybe the best would be to have next config options

```yml
surname-request-askplayers: true/false # when priest try to set someone's surname, if this is true, it will require confirmation by target player/s
surname-request-askplayers-both: true/false # if this is true, then both players who are married to each other need to confirm surname change requested by priest
```

**How the feature is useful**
Because it will prevent priests randomly setting player's surnames to something bad, it's easy to exploit without this SO much

**Comment by MotikaCraft-TheJoshua** [comment]
@GeorgH93 

hello
i have tested this
i used latest build from spigotmc

this is my config part

```yml
Marriage:
  # Defines if players need to get married by a priest or if they can marry each other on their own.
  RequirePriest: true
  # This option defines if a priest is needed to divorce 2 players or if they can divorce on their own.
  # Options: true, false, auto (auto will copy the RequirePriest value)
  DivorceRequiresPriest: false
  # Max numbers of partners that a player can have. Values < 1 disable the limit.
  MaxPartners: 1
  # This setting disables the "/marry setpriest" command players can still be promoted to a priest with the "marry.priest" permission.
  DisableSetPriestCommand: true
  Surnames:
    Enable: true
    Force: false
    # Surname requirements
    AllowColors: false
    AllowedCharacters: A-Za-z
    BannedNames: []
    # Values below 3 will be set to 3
    MinLength: 3
    # Values below the in length will be set to the min length
    MaxLength: 16
    # Options: None, Player, BothPlayers
    Confirmation: BothPlayers
  # Defines if marriages should be announced to all players.
  AnnounceOnMarriage: true
  # Defines if divorces should be announced to all players. auto mirrors the AnnounceOnMarriage setting
  AnnounceOnDivorce: auto
  Confirmation:
    Enable: true
    AutoDialog: true
    BothPlayersOnDivorce: false
    OtherPlayerOnSelfDivorce: false
```

It does not work, anyone can change anyone's surname without confirmation

I have also tried setting "bothplayers"
