### ISSUE TITLE
Add new PAPI placeholder - %marriagemaster_married_howlong% - or whatever fits best to be called

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [GeorgH93/MarriageMaster#365]
### Feature request

**Feature description**
Simply invent new placeholder that will check date and time since when player is CURRENTLY married (if he is so), and compare it to current date and time and display it when this placeholder is parsed - i only give it as rough example, it should not be called "_howlong" but something like "_time" or idk...

i think there should be somewhere in language of locale whatever file is called... a way to format this

```yml
married_time_format:
    years: "&6{years}&ey "
    months: "&6{months}&eM "
    days: "&6{days}&ed "
    hours: "&6{hours}&eh "
    minutes: "&6{minutes}&em"
    main: "{years}{months}{days}{hours}{minutes}"
```

so here as you can see we can configure how each time period should be displayed inside of "main", because "main" will be displayed when we parse `%marriagemaster_married_time%` placeholder

I think this approach is best because of SPACING! please consider this or give us better solution

```
/papi parse me %marriagemaster_married_time%
output: 5m 2d 10m
```

**How the feature is useful**
I think this would benefit to a plugin staying so much on the server, it'll make really neat feature to have and it's long term thing!
