### ISSUE TITLE
[PlaceholderApi] Error on PAPI startup, containing mm related messages (?)

### ISSUE THREAD

**Issue by MithrandirCraft** [GeorgH93/MarriageMaster#72]
I may report this to PAPI if requested, allthough I get the sensation marriagemaster is related to this issue.

Spigot: 1.13.2
MarriageMaster: 2.0.5-RC3-Release
Error log: https://gist.github.com/MithrandirCraft/d3f1f39d738d95ffec64ab170aa3a5e0

**Comment by MithrandirCraft** [comment]
yeah... placeholders are also pretty much broken, but I'm guessing that's been reported a few times already
![imagen](https://user-images.githubusercontent.com/6623704/61580305-bc63e300-ab10-11e9-952c-a908417fce9f.png)

**Comment by GeorgH93** [comment]
Please remove the PAPI eCloud extension. It is not compatible and not needed with Marriage Master v2.
Also you can find the new Placeholder names here: https://github.com/GeorgH93/MarriageMaster/wiki/Placeholders

**Comment by MithrandirCraft** [comment]
I'm guessing you mean this:
**
![imagen](https://user-images.githubusercontent.com/6623704/61580558-dd7a0300-ab13-11e9-8b2e-cca4876d2737.png)
**
*removed

Thanks for the wiki hint :)

**Comment by GeorgH93** [comment]
Yes, that should be the file, looks like it using a slight different name than what my plugin checks for.

**Comment by MithrandirCraft** [comment]
![imagen](https://user-images.githubusercontent.com/6623704/61724550-815eeb00-ad6e-11e9-8337-889ae03f2043.png)
Are these placeholders well formated? They don't seem to work from ChatControl.

**Comment by GeorgH93** [comment]
ChatControl uses PlaceholderAPI, so it should be % instead of {}. `%marriagemaster_heart% %marriagemaster_partner%`

**Comment by MithrandirCraft** [comment]
I've always used curly brackets { since ChatControlPro states it's necessary, without any issues:
![imagen](https://user-images.githubusercontent.com/6623704/61730658-203d1480-ad7a-11e9-99d2-75532315784e.png)
I tried %'s but they don't work either. I pretty much tried every possible combination.

**Comment by GeorgH93** [comment]
Please check your log if Marriage Master has successfully hooked into PlaceholderAPI (there should be this message during the Marriage Master startup: `[MarriageMaster] PlaceholderAPI hook was successfully registered!`).

I have just tested it with the latest free version of the plugin. It's working with these settings in ChatControl:
```
Chat:
  Formatter:
    Enabled: true
    Message_Format: '%marriagemaster_statusheart% %pl_prefix%player:%pl_suffix %message'
```

**Comment by MithrandirCraft** [comment]
I'm using it inside one of these chatcontrol chat pop ups, in formatting.ym Formats, the name shows some information, including marriage:
```
    Player:
      Message: '{nick} '
      Hover_Event:
        Action: SHOW_TEXT
        Values:
        - '&8*-----* &f{player} &8*-----*'
        - '&7Rango/s&8: &f{pl_group}'
        - '&7Mundo: &f{world}'
        - '&7Pareja: %marriagemaster_statusheart%'
```
![imagen](https://user-images.githubusercontent.com/6623704/61740709-98fa9b80-ad8f-11e9-9a05-9da4767d1932.png)
Damn, ever since the update everything from marriage broke u_u
