### ISSUE TITLE
Higher hug titlemsg show time

### ISSUE THREAD

**Issue by TheoRetisch1** [GeorgH93/MarriageMaster#78]
The message at /hug flashes too briefly to be realized if you don't pay attention to it permanently. Could you display the message longer? I would suggest the following: 0.5 fade in, 4 sec showing and 0.5 sec fade out. It would be even more fun if you could configure the display duration time in the config!

**Comment by GeorgH93** [comment]
You can configure it in the language file by adding a new `<MessageName>_Parameters` key like this:
```
    Hug:
      GotHugged: "[\"\",{\"text\":\"&eYour partner has hugged you!\"}]"
      GotHugged_SendMethod: "title"
      GotHugged_Parameters: "{\"subtitle\":false,\"fadeIn\":10,\"stay\":80,\"fadeOut\":10}"
```
The times are in ticks.

**Comment by TheoRetisch1** [comment]
That's genius! Very variable your plugin, could you also tell me how to adjust the size of the title?

**Comment by TheoRetisch1** [comment]
Or if editing the title in Minecraft is not possible (I can't find anything about it) how the hell do I make the bossbarmsg stay visible longer? I'm too stupid when it comes to using the JSON format. I hope I'm not overusing your help with xD.

**Comment by GeorgH93** [comment]
> 
> 
> That's genius! Very variable your plugin, could you also tell me how to adjust the size of the title?

You use the smaller titles by setting the subtitle flag to true like that:
```
    Hug:
      GotHugged: "[\"\",{\"text\":\"&eYour partner has hugged you!\"}]"
      GotHugged_SendMethod: "title"
      GotHugged_Parameters: "{\"subtitle\":true,\"fadeIn\":10,\"stay\":80,\"fadeOut\":10}"
```



> 
> 
> Or if editing the title in Minecraft is not possible (I can't find anything about it) how the hell do I make the bossbarmsg stay visible longer? I'm too stupid when it comes to using the JSON format. I hope I'm not overusing your help xD.

The boss-bar customization is currently not implemented (will probably be done with v2.1).

**Comment by TheoRetisch1** [comment]
Thank you for the quick response! If I set the subtitle flag to true no message is send:
```
    Hug:
      GotHugged: "[\"\",{\"text\":\"&eDein Partner hat dich umarmt!\"}]"
      GotHugged_SendMethod: "title"
      GotHugged_Parameters: "{\"subtitle\":true,\"fadeIn\":10,\"stay\":80,\"fadeOut\":10}"
```
However the two other methods work:
```
    Hug:
      GotHugged: "[\"\",{\"text\":\"&eDein Partner hat dich umarmt!\"}]"
      GotHugged_SendMethod: "title"
      GotHugged_Parameters: "{\"subtitle\":false,\"fadeIn\":10,\"stay\":80,\"fadeOut\":10}"
```
-> sends a giant title nobody can read
```
    Hug:
      GotHugged: "[\"\",{\"text\":\"&eDein Partner hat dich umarmt!\"}]"
      GotHugged_SendMethod: "action_bar"
      GotHugged_Parameters: "{\"subtitle\":false,\"fadeIn\":10,\"stay\":80,\"fadeOut\":10}"
```
-> sends a perfectly small action_bar title, that vanishes away too quickly.
