### ISSUE TITLE
The config setting range does not work

### ISSUE THREAD

**Issue by TheoRetisch1** [GeorgH93/MarriageMaster#99]
Operations specified with -1 or 0 in the config, e.g. /marry gift do not work. There is a message that a minimum proximity of -1 blocks is required. This problem can only be solved with the permission marry.bypass.rangelimit. 

MarriageMaster: 2.0.16
Paper 1.13.2 - 648

```
# Ranges for actions
# -1 no range limit and no world limit, 0 no range limit but in the same world, >= 1 range limit in meters/blocks
Range:
  Marry: 25
  Divorce: -1
  Backpack: 5
  Gift: -1
  Kiss: 0
  KissInteract: 25
  Hug: 5
  HearthVisible: 128
  BonusXP: 10
  Heal: 2
```
